exclude: '^uvtools/data/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=1000']
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: ['--fix=no']

-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-quotes
#          - flake8-comprehensions
          - flake8-builtins
          # - flake8-eradicate
          - pep8-naming
          - flake8-docstrings
          - flake8-rst-docstrings
          - flake8-rst
          # - flake8-copyright

# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     - id: black

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]


- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  -   id: pyupgrade
      args: [--py38-plus]
